SELECT
    YEAR(DIFFERENTIATION_DATE) YEAR,
    ((SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA
     WHERE YEAR(DIFFERENTIATION_DATE) = YEAR)
     - SIZE_OF_COLONY) YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR(DIFFERENTIATION_DATE), YEAR_DEV