WITH RECURSIVE TMP AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TMP
    WHERE HOUR < 23
)
SELECT T.HOUR, COUNT(A.ANIMAL_ID) COUNT
FROM TMP T
LEFT JOIN ANIMAL_OUTS A
ON T.HOUR = HOUR(A.DATETIME) 
GROUP BY T.HOUR
ORDER BY T.HOUR